Bump copyright to 2020

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,3 +1,8 @@
+#          Copyright Rein Halbersma 2014-2020.
+# Distributed under the Boost Software License, Version 1.0.
+#    (See accompanying file LICENSE_1_0.txt or copy at
+#          http://www.boost.org/LICENSE_1_0.txt)
+
 language: cpp
 os: linux
 dist: bionic
@@ -229,7 +234,7 @@ after_success:
 - |
   if [[ "${CODE_COVERAGE}" == "true" ]]; then
     lcov --directory . --capture --output-file coverage.info
-    bash <(curl -s https://codecov.io/bash) -f coverage.info
+    bash <(curl -s https://codecov.io/bash) -v -f coverage.info || echo 'Codecov failed to upload'
   fi
 
 notifications:
